import { Link, useLocation } from "wouter";
import { ShieldCheck } from "lucide-react";
import { Button } from "./ui";
import { useEffect, useState } from "react";
import { cn } from "@/lib/utils";

const NAV_SECTIONS = [
  { id: "how-it-works", label: "How it Works" },
  { id: "about-eu-ai-act", label: "About EU AI Act" },
];

export function Layout({ children }: { children: React.ReactNode }) {
  const [location, setLocation] = useLocation();
  const [activeSection, setActiveSection] = useState<string | null>(null);

  useEffect(() => {
    if (location !== "/") {
      setActiveSection(null);
      return;
    }

    const observer = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setActiveSection(entry.target.id);
          }
        }
      },
      { rootMargin: "-40% 0px -40% 0px", threshold: 0 },
    );

    const ids = NAV_SECTIONS.map((s) => s.id);
    const elements = ids.map((id) => document.getElementById(id)).filter(Boolean) as HTMLElement[];
    elements.forEach((el) => observer.observe(el));

    return () => observer.disconnect();
  }, [location]);

  const handleAnchorClick = (e: React.MouseEvent<HTMLAnchorElement>, hash: string) => {
    e.preventDefault();
    if (location !== "/") {
      setLocation("/");
      setTimeout(() => {
        document.getElementById(hash)?.scrollIntoView({ behavior: "smooth" });
      }, 100);
    } else {
      document.getElementById(hash)?.scrollIntoView({ behavior: "smooth" });
    }
  };

  return (
    <div className="min-h-screen flex flex-col relative overflow-x-hidden">
      <div className="fixed top-[-20%] left-[-10%] w-[50%] h-[50%] rounded-full bg-primary/10 blur-[120px] pointer-events-none -z-10" />
      <div className="fixed bottom-[-20%] right-[-10%] w-[50%] h-[50%] rounded-full bg-accent/20 blur-[120px] pointer-events-none -z-10" />

      <header className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/60 backdrop-blur-xl">
        <div className="container mx-auto px-4 md:px-8 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 transition-transform hover:scale-105 active:scale-95">
            <div className="bg-primary/20 p-2 rounded-lg">
              <ShieldCheck className="w-5 h-5 text-primary" />
            </div>
            <span className="font-display font-bold text-lg hidden sm:inline-block">
              AI Act <span className="text-primary">Checker</span>
            </span>
          </Link>

          <nav className="hidden md:flex items-center gap-8">
            {NAV_SECTIONS.map((section) => (
              <a
                key={section.id}
                href={`#${section.id}`}
                onClick={(e) => handleAnchorClick(e, section.id)}
                className={cn(
                  "text-sm font-medium transition-all duration-200 relative py-1",
                  activeSection === section.id
                    ? "text-primary"
                    : "text-foreground/85 hover:text-white",
                )}
              >
                {section.label}
                <span
                  className={cn(
                    "absolute -bottom-0.5 left-0 h-0.5 bg-primary rounded-full transition-all duration-200",
                    activeSection === section.id ? "w-full" : "w-0",
                  )}
                />
              </a>
            ))}
          </nav>

          <div className="flex items-center gap-4">
            <Link href="/assessment" className="inline-block">
              <Button size="sm" className="rounded-full px-6">
                Start Assessment
              </Button>
            </Link>
          </div>
        </div>
      </header>

      <main className="flex-1 w-full">
        {children}
      </main>

      <footer className="border-t border-border bg-card/30 mt-auto">
        <div className="container mx-auto px-4 py-12 md:py-16 flex flex-col items-center text-center">
          <ShieldCheck className="w-8 h-8 text-muted-foreground mb-6" />
          <p className="text-sm font-medium text-foreground mb-2">
            Based on EU Regulation 2024/1689 (EU Artificial Intelligence Act)
          </p>
          <p className="text-xs text-muted-foreground max-w-2xl">
            Disclaimer: This tool provides informational guidance only and does not constitute legal advice. 
            Risk classifications and obligations generated by this tool should be verified by qualified legal counsel 
            before making compliance decisions.
          </p>
          <div className="mt-8 flex items-center gap-6 text-sm text-muted-foreground">
            <a href="#" className="hover:text-foreground transition-colors">Privacy Policy</a>
            <a href="#" className="hover:text-foreground transition-colors">Terms of Service</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
